import React from 'react';

interface GeneratedArticleProps {
    title: string;
    content: string;
    onClose: () => void;
}

export const GeneratedArticle: React.FC<GeneratedArticleProps> = ({ title, content, onClose }) => {
    return (
        <div className="mt-6 bg-white/60 backdrop-blur-md rounded-xl p-6 border border-white/40 shadow-lg relative animate-fade-in">
            <button
                onClick={onClose}
                className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 transition-colors"
            >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
            <h3 className="text-xl font-bold text-gray-800 mb-4 pr-8">{title}</h3>
            <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-wrap leading-relaxed">
                {content}
            </div>
            <div className="mt-4 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
                Generated by AI (Placeholder)
            </div>
        </div>
    );
};
